### ISSUE TITLE
`register_owner` concern

### ISSUE THREAD

**Issue by bufo24** [casper-ecosystem/enhanced-nft#216]
I am experimenting with the CEP78 contract, and also with the ReverseOwnerLookUp. It works well, but the only concern I have is that every account has to be registered before being able to receive a token. For a free market, this is quite difficult to achieve. 

I am wondering how you could see this happen in a nice way, that the potential owners are not restricted in any way on receiving a token.

I am planning to work with this contract and I need the ReverseOwnerLookUp to integrate with our existing software, but with the `register_owner` thing, I am doubting a bit.

**Comment by darthsiroftardis** [comment]
@bufo24 well, it depends, if you don't want to have a barrier for entry in terms of cost, then I suggest disabling the reverse lookup altogether. However, we have to be able to give you a page table initially to ensure that as you ownership of tokens increases you don't then lose the ability to freely trade those tokens due to a rise in gas costs for transferring each token. The page table, and the individual pages are essential in maintaining a relatively stable gas cost regardless of how many tokens an Account would own.

What exactly is your use case here, I think its worth exploring options or a path forward that doesn't have you relying on the reverse look up
