### ISSUE TITLE
version bumps 1.4

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/enhanced-nft#228]
version update for  all code, logs and readmes relevant for v1.4

**Comment by gRoussac** [comment]
@RitaMAllenCA @darthsiroftardis code, toml files, changelog and readme were updated on branch feature-1.4. Please check with @ACStoneCL that every of those files are correctly updated for release on documentation point of view.

We mainly added two features

- acl whitelisting instead of contract whitelisting
- filter (callback) support for coming cep-82 

Thanks

**Comment by ACStone-MTS** [comment]
Just took a look through the feature branch and the documentation looks good to me.
