### ISSUE TITLE
V1.1 - CEP-78 Gas Cost Stabilization

### ISSUE THREAD

**Issue by gskerry** [casper-ecosystem/enhanced-nft#73]
gas cost of minting tokens should be consistent regardless of how many have previously been minted; currently the costs can be cumulative due to ownership tracking implementation details.

**Comment by gyroflaw** [comment]
I think the problem comes from the data structure the CEP78 is using for `owned_tokens`.
Since the `Vector` needs to be serialized before saved, it requires compute gas to replace the whole size of the owned tokens.
So that means, if I want to transfer to or from a user who owns many tokens, the gas price gets higher than the others.
The more owned tokens, the much gas fee required.

So I think it is better to use Dictionary for `owned_tokens`, to be mapped `index => token ID`, where `index` is in range of `[0, balances[owner]]`.

**Comment by Ehsan4490** [comment]
Hi
When this issue will solve?

**Comment by gskerry** [comment]
Closing as code-complete.
