### ISSUE TITLE
Extend get_verified_caller to point to contract_package_hash

### ISSUE THREAD

**Issue by gskerry** [casper-ecosystem/enhanced-nft#79]
believe an Arcadia developer reported this.  Will be a challenge to external developers wanting to adopt CEP-78

Requires retooling each version of off-chain smart contract.  Want to address for adaptability.

**Comment by gskerry** [comment]
(Raised by Arcadia team 10/18)

**Comment by RitaMAllenCA** [comment]
@darthsiroftardis need an estimate

**Comment by deuszex** [comment]
`get_verified_caller` currently points to AccountHash in case of Session, and ContractHash in the other cases, and returns them as a Key. We want to change the ContractHash to a ContractPackageHash? Or just add ContractPackageHash as well, so that it returns both ContractHash and ContractPackageHash? 
@gskerry @darthsiroftardis
